// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhq81MTHXC4zR5NUt7CfGKosabbyK-7EA',
    appId: '1:1054522877458:web:41e7a337fa027910671acb',
    messagingSenderId: '1054522877458',
    projectId: 'yumswipe',
    authDomain: 'yumswipe.firebaseapp.com',
    storageBucket: 'yumswipe.firebasestorage.app',
    measurementId: 'G-QX39KSS9B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3La_imThtMvwvf-47isar3k2vHYZ1gQ',
    appId: '1:1054522877458:android:9b81cf1d4f98c14e671acb',
    messagingSenderId: '1054522877458',
    projectId: 'yumswipe',
    storageBucket: 'yumswipe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwraRyvWw1h10lLYjJbLuvmkPMY2cuhU0',
    appId: '1:1054522877458:ios:0b0daecfd77eb2c2671acb',
    messagingSenderId: '1054522877458',
    projectId: 'yumswipe',
    storageBucket: 'yumswipe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwraRyvWw1h10lLYjJbLuvmkPMY2cuhU0',
    appId: '1:1054522877458:ios:0b0daecfd77eb2c2671acb',
    messagingSenderId: '1054522877458',
    projectId: 'yumswipe',
    storageBucket: 'yumswipe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhq81MTHXC4zR5NUt7CfGKosabbyK-7EA',
    appId: '1:1054522877458:web:43c4ae9232abbd5e671acb',
    messagingSenderId: '1054522877458',
    projectId: 'yumswipe',
    authDomain: 'yumswipe.firebaseapp.com',
    storageBucket: 'yumswipe.firebasestorage.app',
    measurementId: 'G-7HVPVQKQTQ',
  );
}
